
<?php
	if((isset($_GET['erro'])) && $_GET['erro'] == 'cv') {
?>
	<div class="alert alert-danger text-center" role="alert">
  <span class="font-weight-bold">O carrinho de produtos NÃO pode estar vaziu!</span>
</div>
<?php
	}
?>

<?php 
	if((isset($_GET['cad'])) && $_GET['cad'] == 'ok') {
?>
<form method="post" action="/menu/emitir?tipo=entregador" target="_blank">
<div class="alert alert-success text-center" role="alert">
  <span class="text-success">Cadastrado com sucesso!</span>
  <button class="btn btn-success" name="id_cliente" value="<?= $_SESSION['pedido']['id_pedido'] ?>">Clique aqui para emitir notas!</button>
</div>
</form>
<?php 
}
?>


<form method="post" action="/menu/cadastrar?acao=pedido" id="form-cad">
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
	<h1 class="h2">Cadastro de Pedido</h1>
</div>
<div class="row">	
	<div class="col-sm-3">	
		<div class="form-group">
				<label for="pesq">Código do pedido:</label>	
				<h4 class="form-control text-danger"><?php print_r($this->view->pedido); ?></h4>
		</div>
	</div>
	<div class="col-sm-3">	
		<div class="form-group">
				<label for="pesq">Data:</label>	
				<h4 class="form-control"><?= date('d/m/Y') ?></h4>
		</div>
	</div>
	<div class="col-sm-3">	
		<div class="form-group">
				<label for="pesq">Hora:</label>	
				<h4 class="form-control"><?= date('H:m:s') ?></h4>
		</div>
	</div>

	<div class="col-sm-3">	
		<div class="form-group">
				<label for="pesq">Vendedor:</label>	
				<h4 class="form-control"><?= $this->view->vendedor ?></h4>
		</div>
	</div>

</div>
<hr>
<h2 class="text-center">Dados do Cliente:</h2>
	<hr>	
<div class="containner">	
		<div class="row mx-auto">	
		<div class="for-group col-sm-3">
			<label>Nome/Razão:</label>
			<h4 class="form-control"><?= $this->view->cliente->__get('nome') ?></h4>
		</div>
		<div class="for-group col-sm-3">
			<label>TIPO DO CLIENTE:</label>
			<h4 class="form-control"><?php if($this->view->cliente->__get('tipo_pessoa') == '1') {
				echo "PESSOA FÍSICA";
			}else {
				echo "PESSOA JURÍDICA";
			} ?></h4>
		</div>
		<div class="for-group col-sm-3">
			<label>CPF/CNPJ:</label>
			<h4 class="form-control"><?php if($this->view->cliente->__get('tipo_pessoa') == '1') {
				echo $this->view->cliente->__get('cpf');
			}else {
				echo $this->view->cliente->__get('cnpj');
			} ?></h4>
		</div>
		<div class="for-group col-sm-3">
			<label>RG/INSCRIÇÃO ESTADUAL:</label>
			<h4 class="form-control"><?php if($this->view->cliente->__get('tipo_pessoa') == '1') {
				echo $this->view->cliente->__get('rg');
			}else {
				echo $this->view->cliente->__get('insc_estadual');
			} ?></h4>
		</div>


</div>
<?php
	if(count($this->view->itens) != 0){
?>
<hr>
<div id="pedidos" class="mx-auto" style="max-width: 600px;">
	<h3 class="text-center">Itens do último pedido: <?php 
	$data = new DateTime($this->view->itens[0]['dt_pedido']);
	$hora = $this->view->itens[0]['hr_pedido'];
	echo $data->format('d/m/Y').' às '.$hora;

	?></h3>
	<hr>
	<table class="table table-striped table-responsive-sm">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Descrição do Produto</th>
      <th scope="col">Validade</th>
    </tr>
  </thead>
  <tbody>
  	<?php
  		foreach ($this->view->itens as $key => $item) {
  		$key ++;
  	?>
    <tr>
      <th scope="row"><?= $key ?></th>
      <td><?= $item['ds_produto'] ?></td>
      <td><?= $item['dt_validade'] ?></td>
    </tr>

    <?php
    	}
    ?>
  </tbody>
</table>
</div>
<?php
	}
?>
<hr>
<div>
<h3 class="text-center">Dados do Pedido:</h3>
<hr>
<div class="row">
	<div class="col-sm-6">
		<label>Endereço de entrega:</label>
		<div class="input-group">
  <select class="custom-select" name="id_entrega">
    <option value="-10">Retirado no local</option>
    <?php
    	foreach ($this->view->enderecos as $key => $endereco) {
    ?>
    <option value="<?= $endereco['cd_logradouro']?>"><?= $endereco['endereco']?></option>
  	<?php
  		}
  	?>
  </select>
  <div class="input-group-append">
    <button class="btn btn-outline-secondary" type="button">Novo Endereço</button>
  </div>
</div>
		
	</div>	
</div>
</div>
<hr>

<div id="carrinho">
	<h3 class="text-center">Carrinho</h3>
	<hr>
	<div class="container-fluid pb-4 pt-4" style="background: #f5f5f0;">
		<table class="table-responsive-sm">
		<div class="container">
			<thead>
				<tr>
					<th class="pr-4">
						<label for="descProd">Código/Descrição do Produto:</label>
						
					</th>
				
				
					<th class="pr-4">
						<label for="descProd">Valor Unitário:</label>
					
					</th>
				
				
					<th class="pr-4">
						<label for="descProd">Quantidade:</label>
						
					</th>
				
			
					<th class="pl-5">
						<label>Adicionar Produto:</label>
						
					</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td class="pr-4">
						<select class="form-control selectBusca" id="produto">
							<option  value="-10" id="escolha">Escolha um produto</option>
						<?php
							foreach ($this->view->produtos as $key => $produto) {					
						?>
							<option value="<?=$produto['cd_produto']?>"><?=$produto['ds_produto']?></option>
						<?php
							}
						?>	
						</select>
<script type="text/javascript">
	$('.selectBusca').select2({
});
</script>						

					</td>
					<td class="pr-4">
						<input type="text" class="form-control" id="preco" disabled>		
					</td>
					<td class="pr-4">
						<input type="number" class="form-control" id="quantidade">		
					</td>
					<td class="pl-5">
						<button class="btn btn-info form-control" type="button" id="adicionar">Adicionar</button>
					</td>	

				</tr>

			</tbody>
		</div>
	</table>
	<div class="mt-3">
		
	<table class="table table-striped table-responsive-sm">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Código do Produto</th>
      <th scope="col">Descrição do Produto</th>
      <th scope="col">Validade</th>
      <th scope="col">Valor Unitário</th>
      <th scope="col">Quantidade</th>
      <th scope="col">Valor total</th>
      <th scope="col">Ações</th>
    </tr>
  </thead>
  <tbody id="carrinhos">
    
  </tbody>
</table>
	</div>
</div>
</div>
</div>

<div id="botoes" class="mt-5">
	<div class="row">
		<div class="col-sm">
			<button type="button" id="cancelar" class="btn btn-danger col-sm pt-3 pb-3">CANCELAR</button>
		</div>
		<div class="col-sm">
			<button type="submit" class="btn btn-success col-sm pt-3 pb-3" id="cadastrar">CADASTRAR</button>
		</div>
	</div>

</div>	
</form>
<br />
<br />

<script type="text/javascript">
	$(document).ready(function() {
		$("#preco").maskMoney({prefix:'R$ ', allowNegative: true, thousands:'.', decimal:',', affixesStay: false});
		renderCarrinho();
	});
	$('#produto').change(function() {
		var id_produt = $('#produto').val();
		if(id_produt > 0){
			$('#preco').val('');
			$('#quantidade').val('');
		}
		$.ajax({
			url: '/menu/pedido/produtos',
			method: 'POST',
			datatype: 'html',
			data: {id_produto: id_produt}, 
			success: function(data) {
				$('#preco').empty().val('R$ '+data).focus();
				$('#quantidade').empty().focus();

			}

		});
	});


</script>

<script type="text/javascript">
	$('#adicionar').on('click',function() {
		var id_produt = $('#produto').val();
		var quantidade = $('#quantidade').val();
		if(quantidade <= 0){
			alert('Quantidade de produtos inválida!');
		}else{
			$.ajax({
				url: '/menu/pedido/addCarrinho',
				method: 'POST',
				datatype: 'html',
				data: {action: 'add', id_produto: id_produt, qtd: quantidade},
				success: function() {
					$('#quantidade').val('');
					renderCarrinho();
					$('#produto').focus();
				}
			});	
		}
		
	})

</script>
<script type="text/javascript">
	function renderCarrinho(){
		$.ajax({
				url: '/menu/pedido/addCarrinho',
				method: 'POST',
				datatype: 'html',
				data: {action: 'render'},
				success: function(data) {
					$('#carrinhos').empty().append(data);
				}
			});	
	}
</script>

<script type="text/javascript">
	
	function excluir(id) {
		if(confirm('Deseja mesmo remover esse produto?')){
			$.ajax({
				url: '/menu/pedido/addCarrinho',
				method: 'POST',
				datatype: 'html',
				data: {action: 'excluir',id_produto: id},
				success: function() {
					renderCarrinho();	
				}
			});		
		}
		
	}

</script>

	<script type="text/javascript">
		$('#cancelar').on('click', function() {
			$(location).attr('href', '/menu/selecionar');
		})
	</script>