<?php 
	if(isset($_GET['erro']) && $_GET['erro'] == 'nome'){
?>
<div class="alert alert-danger text-center" role="alert">
  Atenção, o NOME OU RAZÃO SOCIAL não podem ser NULOS ou INFERIORES A 3 CARACTERES!
</div>
<?php
	}
	if(isset($_GET['erro']) && $_GET['erro'] == 'ddd1'){
?>
<div class="alert alert-danger text-center" role="alert">
  <span class="text-danger">Atenção, os dados informados como CPF ou RG já foram cadastrados!</span>
</div>
<?php }
if(isset($_GET['erro']) && $_GET['erro'] == 'ddd2'){
?>
<div class="alert alert-danger text-center" role="alert">
  <span class="text-danger">Atenção, os dados informados como CNPJ ou INSCRIÇÃO ESTADUAL já foram cadastrados!</span>
</div>
<?php }
if(isset($_GET['cad']) && $_GET['cad'] == 'ok'){
?>
<div class="alert alert-success text-center" role="alert">
  <span class="text-success">Cadastrado com sucesso!</span>
  <button class="btn btn-success">Clique aqui para fazer um pedido!</button>
</div>
<?php }
?> 
<form method="post" action="/menu/cadastrar?acao=cliente" id=	"form-cad">
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
	<h1 class="h2">Cadastro de Cliente</h1>
</div>

<div class="row">
	<div class="col-sm-6">
    	<div class="card text-center">
    		<label for="fisica">
      			<div class="card-body">
        			<i class="card-title fas fa-user" style="font-size: 50pt"></i>
        			<p class="card-text">Pessoa Física</p>
       				<input type="radio" id="fisica" value="1" name="tipo_pessoa" class="form-control" checked="" >
      			</div>
      		</label>	
    	</div>
  </div>
  <div class="col-sm-6 text-center">
  	<div class="card">
    	<label for="juridica">
	    	<div class="card-body" for="juridica">
	        	<i class="card-title fas fa-balance-scale" style="font-size: 50pt"></i>
	        	<p class="card-text">Pessoa Jurídica</p>
	        	<input id="juridica" type="radio" value="2" name="tipo_pessoa" class="form-control">
	      	</div>
  		</label>
    </div>
  </div>
</div>

<hr>

<div  class=" mt-2" >
	<div id="dados" class="row">
	<div class="col-sm-3">
		<br>
	</div>
	<div id="fisi" class="col-sm-6">
		<div class="form-group">
			<label for="nome">Nome:</label>	
			<input id="nome" type="text" class="form-control text-uppercase" name="nome" minlength="3" maxlength="100">
		</div>
		<div class="form-group">
			<label for="cpf">CPF:</label>	
			<input id="cpf" type="text" class="form-control text-uppercase" name="cpf" maxlength="11">
		</div>
		<div class="form-group ">
			<label for="rg">RG:</label>	
			<input id="rg" type="text" name="rg" class="form-control text-uppercase" name="rg">
		</div>
	</div>
	
	<div id="juri" class="col-sm-6 d-none" >
		<div class="form-group">
			<label for="razao">Razão Social:</label>	
			<input id="razao" type="text" name="razao" class="form-control text-uppercase" name="razao" minlength="3" maxlength="100">
		</div>
		<div class="form-group ">
			<label for="cnpj">CNPJ:</label>	
			<input id="cnpj" type="text" name="cnpj" class="form-control text-uppercase" name="cnpj">
		</div>
		<div class="form-group ">
			<label for="insc">Inscrição Estadual:</label>	
			<input id="insc" type="text" name="insc_estadual" class="form-control text-uppercase" name="insc">
		</div>
	</div>
	</div>
	<hr>
</div>
<div id="contato">
	<h2 class="text-center">Contatos</h2>
	<hr>
	<div class="row text-center">
		<table class="table table-striped table-responsive-sm">
			<div class="col-sm-12">
				<thead>
					<tr class="text-center">
						<th scope='col'>#</th>
						<th scope='col'>Telefone</th>
						<th scope='col'>Tipo de contato</th>
					
					</tr>
				</thead>	
				<form method="post" name="contatos" action="/menu/cadastrar/?acao=cliente">
				<tbody  id="contatos">
					<tr>
						<td>1</td>
						<td>
							<input type="text" class="form-control telefone" name="tell1">
						</td>
						<td>
							<select class="form-control" name="tipotell1">
								<?php 
									foreach ($this->view->tipoContatos as $key => $tipoContato) { ?>
					
								<option value="<?= $tipoContato['cd_tipo']; ?>"><?= $tipoContato['nm_tipo']; ?></option>

								<?php
									}
								?>
							</select>
						</td>
					

					</tr>


					<tr>
						<td>2</td>
						<td>
							<input type="text" class=" form-control telefone" name="tell2">
						</td>
						<td>
							<select class="form-control" name="tipotell2">
								<?php 
									foreach ($this->view->tipoContatos as $key => $tipoContato) { ?>
					
								<option value="<?= $tipoContato['cd_tipo']; ?>"><?= $tipoContato['nm_tipo']; ?></option>

								<?php
									}
								?>
							</select>
						</td>
						


					</tr>


					<tr>
						<td>3</td>
						<td>
							<input type="text" class="form-control telefone" name="tell3">
						</td>
						<td>
							<select class="form-control" name="tipotell3">
								<?php 
									foreach ($this->view->tipoContatos as $key => $tipoContato) { ?>
					
								<option value="<?= $tipoContato['cd_tipo']; ?>"><?= $tipoContato['nm_tipo']; ?></option>

								<?php
									}
								?>
							</select>
						</td>
						


					</tr>
				</tbody>
			</form>
			</div>
		</table>
	</div>	
	<hr>
</div>
<div id="endereco">
	<h2 class="text-center">Endereços</h2>
	<hr>
	<div class="row">
		<div class="col-sm-12">
			<div class="form-group">
				<label for="cep">CEP:</label>
				<div class="d-flex">
					<input class="form-control col-sm-3 " name="cep" type="text" id="cep" value="" size="10" maxlength="9" onblur="pesquisacep()">
				</div>
			</div>
		</div>
	</div>
	<div class="row border pt-3">
		<div class="col-sm-4">
			<div class="form-group">
				<label for="uf">Unidade Federativa:</label>
				<select id="uf" class="form-control" name="uf">
					<?php foreach ($this->view->ufs as $key => $uf) { ?>
					
					<option value="<?= $uf['sg_uf']; ?>"> <?= $uf['sg_uf']; ?></option>
				<?php }	?>
				</select>
			</div>
		</div>
		<div class="col-sm-4">
			<div class="form-group">
				<label for="cidade">Cidade:</label>
				<select id="cidade" class="form-control" name="cidade">
					<?php foreach ($this->view->cidades as $key => $cidade) { ?>
					
					<option value="<?= $cidade['nm_cidade']; ?>"> <?= $cidade['nm_cidade']; ?></option>
				<?php }	?>
				</select>
			</div>
		</div>
		<div class="col-sm-4">
			<div class="form-group">
				<label for="bairro">Bairro:</label>
				<select id="bairro" class="form-control" name="bairro">
					<?php foreach ($this->view->bairros as $key => $bairro) { ?>
					
					<option value="<?= $bairro['nm_bairro']; ?>"> <?= $bairro['nm_bairro']; ?></option>
				<?php }	?>
				</select>
			</div>
		</div>		

			<div class="col-sm">
				<div class="form-group">
					<label for="rua">Logradouro:</label>
					<input type="text" id="rua" class="form-control" name="logradouro" >
				</div>
			</div>
			<div class="col-sm">
				<div class="form-group">
					<label for="num">Numero:</label>
					<input type="number" id="num" class="form-control" name="numero">
				</div>
			</div>
			<div class="col-sm">
				<div class="form-group">
					<label for="comple">Complemento:</label>
					<input type="text" id="comple" class="form-control" name="complemento">
				</div>
			</div>
	</div>
	<hr>
</div>		

<div id="botoes" class="mt-5">
	<div class="row">
		<div class="col-sm">
			<button type="reset" class="btn btn-danger col-sm pt-3 pb-3">CANCELAR</button>
		</div>
		<div class="col-sm">
			<button type="submit" class="btn btn-success col-sm pt-3 pb-3" id="cadastrar">CADASTRAR</button>
		</div>
	</div>
</div>	
</form>
<br />
<br />



<script type="text/javascript">

	$(document).ready(function() {
		function juridica() {
			$("#juri").removeClass('d-none');
			$("#fisi").addClass('d-none');
		}
		function fisica() {
			$("#fisi").removeClass('d-none');
			$("#juri").addClass('d-none');
		}

		function escolhaPessoa() {
			if($('#fisica').prop('checked')) {
				fisica();
			}else if($("#juridica").prop('checked')) {
				juridica()
				
			}
		}

		$("#juridica").click(function () {
			escolhaPessoa();
			$('#nome').prop('required',false);
			$('#razao').prop('required',true);
		});

		$("#fisica").click(function () {
			escolhaPessoa();
			$('#nome').prop('required',true);
			$('#razao').prop('required',false);
		});
	});
</script>
<script type="text/javascript">

$("input.telefone")
        .mask("(99) 9999-99999")
        .focusout(function (event) {
            var target, phone, element;
            target = (event.currentTarget) ? event.currentTarget : event.srcElement;
            phone = target.value.replace(/\D/g, ''); //Remove tudo o que não é dígito
            element = $(target);
            element.unmask();
            if(phone.length > 10) {
                element.mask("(99) 9 9999-9999");
            } else if(phone.length == 10 ) {
                element.mask("(99) 9999-99999");
            }else {
            }
        });
</script>
 <script type="text/javascript" >
    function limpa_formulário_cep() {
            //Limpa valores do formulário de cep.
            document.getElementById('rua').value=("");
            document.getElementById('comple').value=("");            
    }

    function meu_callback(conteudo) {
        if (!("erro" in conteudo)) {
            //Atualiza os campos com os valores.
            document.getElementById('rua').value=(conteudo.logradouro);
            document.getElementById('bairro').value=(conteudo.bairro);
            document.getElementById('cidade').value=(conteudo.localidade);
            document.getElementById('uf').value=(conteudo.uf);
            document.getElementById('comple').value=(conteudo.complemento);
        } //end if.
        else {
            //CEP não Encontrado.
            limpa_formulário_cep();
            alert("CEP não encontrado.");
        }
    }
        
    function pesquisacep() {
    	var valor = $('#cep').val();
        //Nova variável "cep" somente com dígitos.
        var cep = valor.replace(/\D/g, '');

        //Verifica se campo cep possui valor informado.
        if (cep != "") {

            //Expressão regular para validar o CEP.
            var validacep = /^[0-9]{8}$/;

            //Valida o formato do CEP.
            if(validacep.test(cep)) {

                //Preenche os campos com "..." enquanto consulta webservice.
                document.getElementById('rua').value="...";	

                //Cria um elemento javascript.
                var script = document.createElement('script');

                //Sincroniza com o callback.
                script.src = 'https://viacep.com.br/ws/'+ cep + '/json/?callback=meu_callback';

                //Insere script no documento e carrega o conteúdo.
                document.body.appendChild(script);
                $('#num').focus()

            } //end if.
            else {
                //cep é inválido.
                limpa_formulário_cep();
                alert("Formato de CEP inválido.");
                $('#cep').focus();
            }
        } //end if.
        else {
            //cep sem valor, limpa formulário.
            limpa_formulário_cep();
        }
    };

    $(document).ready(function(){
		$("#cep").mask("99.999-999");
	});

	$(document).ready(function () { 
        var $seuCampoCpf = $("#cpf");
        $seuCampoCpf.mask('000.000.000-00', {reverse: true});
         $('#rg').mask('99.999.999-A');
    });


    </script>
	<script type="text/javascript">
		$('#form-cad').submit(function() {
			if($('#num').val() == '' || $('#comple').val() ==''){
				$('#rua').prop('require',true);
				$('#bairro').prop('require',true);
			}else {
				return true;
			}
		})

		$(document).ready(function(){	
		$("#cnpj").mask("99.999.999/9999-99");
	});
	</script>