
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
	<h1 class="h2">Seleção de Cliente</h1>
</div>
<label>Pesquisa:</label>
<div class="input-group mb-3">
	<input type="text" class="form-control col-sm-12">
  	<div class="input-group-append">
    	<select class="custom-select " id="inputGroupSelect02">
    		<option selected>Choose...</option>
    		<option value="1">One</option>
    		<option value="2">Two</option>
    		<option value="3">Three</option>
  		</select>
  	</div>
</div>
<div class="text-center">
	<button class="btn btn-info">Pesquisar</button>		
</div>
<hr>
<div class="">
	
</div>