
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
	<h1 class="h2">Seleção de Cliente</h1>
</div>
<label>Pesquisa:</label>
<form action="/menu/pesquisar" method="get">
<div class="input-group mb-3">
	<input type="text" class="form-control col-sm-12" name="pesq">
  	<div class="input-group-append">
    	<select class="custom-select " id="inputGroupSelect02" name="tipo_pesq">
    		<option value="0"selected>NOME</option>
    		<option value="1">TELEFONE</option>
    		<option value="2">CPF</option>
    		<option value="3">RG</option>
        <option value="4">CNPJ</option>
        <option value="5">INSC. ESTADUAL</option>
  		</select>
  	</div>
</div>
<div class="text-center">
	<button class="btn btn-info pl-5 pr-5">Pesquisar</button>		
</div>
</form>
<hr>
<div class="mt-2">
  <table class="table table-striped table-responsive-sm">
    <thead>
      <tr>
        <th scope="col">NOME</th>
        <th scope="col">DATA DE CADASTRO</th>
        <th scope="col">TIPO DE CLIENTE</th>
        <th scope="col">CPF/CNPJ</th>
        <th scope="col">RG/INSC. ESTADUAL</th>
        <th scope="col">TELEFONE</th>
        <th scope="col">AÇÕES</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>PAULO LEITE COSTA</td>
        <td>19/12/2018 12:30:58</td>
        <td>PESSOA FÍSICA</td>
        <td>504.084.648-79</td>
        <td>56.713.233-X</td>
        <td>(13) 9 9620-5206</td>
        <td><button class="btn btn-success">Selecionar</button></td>
      </tr>
      <tr>
        <td>PAULO LEITE COSTA</td>
        <td>19/12/2018 12:30:58</td>
        <td>PESSOA FÍSICA</td>
        <td>504.084.648-79</td>
        <td>56.713.233-X</td>
        <td>(13) 9 9620-5206</td>
        <td><button class="btn btn-success">Selecionar</button></td>
      </tr>
    </tbody>
  </table>
</div>