
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
	<h1 class="h2">Seleção de Cliente</h1>
</div>
<label>Pesquisa por:</label>
<form action="/menu/pesquisar" method="get" id="form-pesq">
<div class="input-group mb-3">
	<div class="input-group-append">
      <select class="custom-select " id="tipo_pesquisa" name="tipo_pesq">
        <option value="0"selected>NOME</option>
        <option value="1">TELEFONE</option>
        <option value="2">CPF</option>
        <option value="3">RG</option>
        <option value="4">CNPJ</option>
        <option value="5">INSC. ESTADUAL</option>
      </select>
    </div>
  <input type="text" class="form-control col-sm-12 " name="pesq" minlength="3" id="pesq">
  	
</div>


<div class="text-center">
	<button class="btn btn-info pl-5 pr-5" id="pesquisar" >Pesquisar</button>		
</div>
</form>
<hr>
<script type="text/javascript">
  $('#pesquisar').on('click', function() {
    var qtd = $('#pesq').val().length;
    if(qtd >=3){
      return true;
    }else {
      return false;
    }
  });

</script>
<?php
  if($this->view->clientes == '' || $this->view->clientes == 'vaziu'){
?>   
<?php
        }else if(count($this->view->clientes) == 0) { ?>          
          <div class="alert alert-danger text-center">
  <span class="text-danger">Nenhum cliente foi encontrado com esses dados!</span>
</div>
<?php 
  }else {
?>
<div class="mt-2">
  <table class="table table-striped table-responsive-sm">
    <thead>
      <tr>
        <th scope="col">NOME</th>
        <th scope="col">DATA DE CADASTRO</th>
        <th scope="col">TIPO DE CLIENTE</th>
        <th scope="col">CPF/CNPJ</th>
        <th scope="col">RG/INSC. ESTADUAL</th>
        <th scope="col">TELEFONE</th>
        <th scope="col">AÇÕES</th>
      </tr>
    </thead>
    <tbody>
      <form method="post" action="/menu/seleciona"> 
        

<?php
        foreach ($this->view->clientes as $key => $cliente) {
        ?>
      <tr>
        <td><?php
        $encoding = 'UTF-8'; // ou ISO-8859-1...
      echo mb_convert_case($cliente['nome'], MB_CASE_UPPER, $encoding); ?></td>
        <td><?= $cliente['data'] ?></td>
        <td><?php 
          if($cliente['tipo'] == 1){
            echo "<span class='text-success'> PESSOA FÍSICA</span>";
          }else {
            echo "<span class='text-info'> PESSOA JURÍDICA</span>";
          }
        ?></td>
        <td><?php if($cliente['cod'] == ''){
          echo "<span class='text-danger'>Não cadastrado</span>";
        }else {
          echo $cliente['cod'];
        } ?></td>
        <td><?php  if($cliente['cod2'] == '') {
         echo "<span class='text-danger'>Não cadastrado</span>";
        }else {
          echo $cliente['cod2'];
        } ?></td>
        <td><?php 
            if($cliente['telefone'] == ''){
              echo "<span class='text-danger'>Não cadastrado</span>";
            }else {
              echo $cliente['telefone'];
            } 
        ?></td>
        <td><button class="btn btn-success" value="<?= $cliente['cd_cliente'] ?>" name="id_cliente">Selecionar</button></td>
      </tr>
      <?php
        }
      ?>

      </form>
    </tbody>
  </table>
</div>
<?php
  }
?>

<script type="text/javascript">
  $('#tipo_pesquisa').change(function(){
    var tipo = $('#tipo_pesquisa').val();
    if(tipo == '1'){
       $('#pesq').addClass('telefone');
    }
  })

</script>

<script type="text/javascript">

$("input.telefone")
        .mask("(99) 9999-99999")
        .focusout(function (event) {
            var target, phone, element;
            target = (event.currentTarget) ? event.currentTarget : event.srcElement;
            phone = target.value.replace(/\D/g, ''); //Remove tudo o que não é dígito
            element = $(target);
            element.unmask();
            if(phone.length > 10) {
                element.mask("(99) 9 9999-9999");
            } else if(phone.length == 10 ) {
                element.mask("(99) 9999-99999");
            }else {
            }
        });
</script>