
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
	<h1 class="h2">Seleção de Cliente</h1>
</div>
<label>Pesquisa:</label>
<form action="/menu/pesquisar" method="get" id="form-pesq">
<div class="input-group mb-3">
	<input type="text" class="form-control col-sm-12" name="pesq" minlength="3" id="pesq">
  	<div class="input-group-append">
    	<select class="custom-select " id="inputGroupSelect02" name="tipo_pesq">
    		<option value="0"selected>NOME</option>
    		<option value="1">TELEFONE</option>
    		<option value="2">CPF</option>
    		<option value="3">RG</option>
        <option value="4">CNPJ</option>
        <option value="5">INSC. ESTADUAL</option>
  		</select>
  	</div>
</div>


<div class="text-center">
	<button class="btn btn-info pl-5 pr-5">Pesquisar</button>		
</div>
</form>
<hr>
<?php
  if($this->view->clientes == ''){
?>   
<?php
        }else if(count($this->view->clientes) == 0) { ?>          
          <div class="alert alert-danger text-center">
  <span class="text-danger">Nenhum cliente foi encontrado com esses dados!</span>
</div>
<?php 
  }else {
?>
<div class="mt-2">
  <table class="table table-striped table-responsive-sm">
    <thead>
      <tr>
        <th scope="col">NOME</th>
        <th scope="col">DATA DE CADASTRO</th>
        <th scope="col">TIPO DE CLIENTE</th>
        <th scope="col">CPF/CNPJ</th>
        <th scope="col">RG/INSC. ESTADUAL</th>
        <th scope="col">TELEFONE</th>
        <th scope="col">AÇÕES</th>
      </tr>
    </thead>
    <tbody>
      <form method="post" action="/menu/seleciona"> 
        

<?php
        foreach ($this->view->clientes as $key => $cliente) {
        ?>
      <tr>
        <td><?= $cliente['nome'] ?></td>
        <td><?= $cliente['data'] ?></td>
        <td><?php 
          if($cliente['tipo'] == 1){
            echo "<span class='text-success'> PESSOA FÍSICA</span>";
          }else {
            echo "<span class='text-info'> PESSOA JURÍDICA</span>";
          }
        ?></td>
        <td><?php if($cliente['cod'] == ''){
          echo "<span class='text-danger'>Não cadastrado</span>";
        }else {
          echo $cliente['cod'];
        } ?></td>
        <td><?php  if($cliente['cod2'] == '') {
         echo "<span class='text-danger'>Não cadastrado</span>";
        }else {
          echo $cliente['cod2'];
        } ?></td>
        <td><?php 
            if($cliente['telefone'] == ''){
              echo "<span class='text-danger'>Não cadastrado</span>";
            }else {
              echo $cliente['telefone'];
            } 
        ?></td>
        <td><button class="btn btn-success" value="<?= $cliente['cd_cliente'] ?>" name="id_cliente">Selecionar</button></td>
      </tr>
      <?php
        }
      ?>

      </form>
    </tbody>
  </table>
</div>
<?php
  }
?>

</script>