<form class="form-signin" method="post" action="/autenticar">
      <div class="text-center mb-4">
        <img class="mb-4" src="img/img_login.png" alt="" width="100" height="100">
        <h1 class="h3 mb-3 font-weight-normal">Área Restrita</h1>
      </div>

      <?php if($this->view->login == 'erro'){ ?>
      <div class="row">
        <div class="col">
          <div class="alert alert-danger text-center"> 
            <span class="text text-danger">Código de acesso e ou senha inválido(s)</span>    
          </div>
          
        </div>
      </div>  
      <?php } ?>


      <div class="form-label-group">
        <input type="text" id="inputAcesso" class="form-control" placeholder="Código de acesso" required autofocus name="acesso">
        <label for="inputAcesso">Código de acesso</label>
      </div>

      <div class="form-label-group">
        <input type="password" id="inputPassword" class="form-control" placeholder="Senha" required name="senha">
        <label for="inputPassword">Senha</label>
      </div>
      <button class="btn btn-lg btn-primary btn-block" type="submit">Acessar</button>
      
      <p class="mt-5 mb-3 text-muted text-center">&copy; 2018-2019</p>
    </form>


    